export const GameScreenId = {
  WELCOME_SCREEN: "WELCOME_SCREEN",
  PLAY_GAME_SCREEN: "PLAY_GAME_SCREEN",
};
export const COLOR_GAME = {
  COLOR_PINK_RED: "#e52554",
};

export const ImageName = {
  BACKGROUND: "BACKGROUND",
  PLAY_BTN: "PLAY_BTN",
  BORDER_CARD: "BORDER_CARD",
  PANEL_WINDOW_POPUP: "PANEL_WINDOW_POPUP",
  ARROW_LEFT_BTN: "ARROW_LEFT_BTN",
  HEADER_GAME_PLAY_GAME: "HEADER_GAME_PLAY_GAME",
  PAUSE_BTN: "PAUSE_BTN",
  HOME_BTN: "HOME_BTN",
  REPLAY_BTN: "REPLAY_BTN",
  DEAD_ICON: "DEAD_ICON",
  BACK_HARDCORE_2: "BACK_HARDCORE_2",
  BACK_HARDCORE_3: "BACK_HARDCORE_3",
  START_0_3: "START_0_3",
  START_1_3: "START_1_3",
  START_2_3: "START_2_3",
  START_3_3: "START_3_3",
};
export const AudioName = {
  CORRECT_AUDIO: "CORRECT_AUDIO",
  INCORRECT_AUDIO: "INCORRECT_AUDIO",
};
